version: "3.9"
services:
  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tarea
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/some_name/
    ports:
      - "5433:5432"

  hadoop:
    container_name: hadoop
    build:
      context: ./Hadoop/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Hadoop/examples:/home/hduser/examples
      #- ./Hadoop/buscador:/home/hduser/buscador
    ports:
      - 9864:9864
      - 9870:9870
      - 8088:8088
      - 9000:9000
      - 8020:8020 
    depends_on:
      - db